#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxxoUserInterface
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataSource")]
	public partial class OksaDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblUye(tblUye instance);
    partial void UpdatetblUye(tblUye instance);
    partial void DeletetblUye(tblUye instance);
    partial void InserttblTeklifler(tblTeklifler instance);
    partial void UpdatetblTeklifler(tblTeklifler instance);
    partial void DeletetblTeklifler(tblTeklifler instance);
    partial void InserttblTalepler(tblTalepler instance);
    partial void UpdatetblTalepler(tblTalepler instance);
    partial void DeletetblTalepler(tblTalepler instance);
    partial void InserttblPunchIsStoku(tblPunchIsStoku instance);
    partial void UpdatetblPunchIsStoku(tblPunchIsStoku instance);
    partial void DeletetblPunchIsStoku(tblPunchIsStoku instance);
    partial void InserttblPunchBand(tblPunchBand instance);
    partial void UpdatetblPunchBand(tblPunchBand instance);
    partial void DeletetblPunchBand(tblPunchBand instance);
    partial void InserttblPunch(tblPunch instance);
    partial void UpdatetblPunch(tblPunch instance);
    partial void DeletetblPunch(tblPunch instance);
    partial void InserttblMalzeme(tblMalzeme instance);
    partial void UpdatetblMalzeme(tblMalzeme instance);
    partial void DeletetblMalzeme(tblMalzeme instance);
    partial void InserttblLazerStok(tblLazerStok instance);
    partial void UpdatetblLazerStok(tblLazerStok instance);
    partial void DeletetblLazerStok(tblLazerStok instance);
    partial void InserttblLazerBand(tblLazerBand instance);
    partial void UpdatetblLazerBand(tblLazerBand instance);
    partial void DeletetblLazerBand(tblLazerBand instance);
    partial void InserttblLazer(tblLazer instance);
    partial void UpdatetblLazer(tblLazer instance);
    partial void DeletetblLazer(tblLazer instance);
    partial void InserttblgenelIsStok(tblgenelIsStok instance);
    partial void UpdatetblgenelIsStok(tblgenelIsStok instance);
    partial void DeletetblgenelIsStok(tblgenelIsStok instance);
    partial void InserttblError(tblError instance);
    partial void UpdatetblError(tblError instance);
    partial void DeletetblError(tblError instance);
    partial void InserttblAbgantIsStoku(tblAbgantIsStoku instance);
    partial void UpdatetblAbgantIsStoku(tblAbgantIsStoku instance);
    partial void DeletetblAbgantIsStoku(tblAbgantIsStoku instance);
    partial void InserttblAbgantBand(tblAbgantBand instance);
    partial void UpdatetblAbgantBand(tblAbgantBand instance);
    partial void DeletetblAbgantBand(tblAbgantBand instance);
    partial void InserttblAbgant(tblAbgant instance);
    partial void UpdatetblAbgant(tblAbgant instance);
    partial void DeletetblAbgant(tblAbgant instance);
    #endregion
		
		public OksaDBDataContext() : 
				base(global::OxxoUserInterface.Properties.Settings.Default.DataSourceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OksaDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OksaDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OksaDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OksaDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblUye> tblUyes
		{
			get
			{
				return this.GetTable<tblUye>();
			}
		}
		
		public System.Data.Linq.Table<tblTeklifler> tblTekliflers
		{
			get
			{
				return this.GetTable<tblTeklifler>();
			}
		}
		
		public System.Data.Linq.Table<tblTedarikci> tblTedarikcis
		{
			get
			{
				return this.GetTable<tblTedarikci>();
			}
		}
		
		public System.Data.Linq.Table<tblTalepler> tblTaleplers
		{
			get
			{
				return this.GetTable<tblTalepler>();
			}
		}
		
		public System.Data.Linq.Table<tblTalepDetay> tblTalepDetays
		{
			get
			{
				return this.GetTable<tblTalepDetay>();
			}
		}
		
		public System.Data.Linq.Table<tblReceteler> tblRecetelers
		{
			get
			{
				return this.GetTable<tblReceteler>();
			}
		}
		
		public System.Data.Linq.Table<tblPunchIsStoku> tblPunchIsStokus
		{
			get
			{
				return this.GetTable<tblPunchIsStoku>();
			}
		}
		
		public System.Data.Linq.Table<tblPunchBandOperator> tblPunchBandOperators
		{
			get
			{
				return this.GetTable<tblPunchBandOperator>();
			}
		}
		
		public System.Data.Linq.Table<tblPunchBandDuraklama> tblPunchBandDuraklamas
		{
			get
			{
				return this.GetTable<tblPunchBandDuraklama>();
			}
		}
		
		public System.Data.Linq.Table<tblPunchBand> tblPunchBands
		{
			get
			{
				return this.GetTable<tblPunchBand>();
			}
		}
		
		public System.Data.Linq.Table<tblPunch> tblPunches
		{
			get
			{
				return this.GetTable<tblPunch>();
			}
		}
		
		public System.Data.Linq.Table<tblMalzeme> tblMalzemes
		{
			get
			{
				return this.GetTable<tblMalzeme>();
			}
		}
		
		public System.Data.Linq.Table<tblLazerStok> tblLazerStoks
		{
			get
			{
				return this.GetTable<tblLazerStok>();
			}
		}
		
		public System.Data.Linq.Table<tblLazerBantOperator> tblLazerBantOperators
		{
			get
			{
				return this.GetTable<tblLazerBantOperator>();
			}
		}
		
		public System.Data.Linq.Table<tblLazerBantDuraklama> tblLazerBantDuraklamas
		{
			get
			{
				return this.GetTable<tblLazerBantDuraklama>();
			}
		}
		
		public System.Data.Linq.Table<tblLazerBand> tblLazerBands
		{
			get
			{
				return this.GetTable<tblLazerBand>();
			}
		}
		
		public System.Data.Linq.Table<tblLazer> tblLazers
		{
			get
			{
				return this.GetTable<tblLazer>();
			}
		}
		
		public System.Data.Linq.Table<tblgenelIsStok> tblgenelIsStoks
		{
			get
			{
				return this.GetTable<tblgenelIsStok>();
			}
		}
		
		public System.Data.Linq.Table<tblError> tblErrors
		{
			get
			{
				return this.GetTable<tblError>();
			}
		}
		
		public System.Data.Linq.Table<tblAbgantIsStoku> tblAbgantIsStokus
		{
			get
			{
				return this.GetTable<tblAbgantIsStoku>();
			}
		}
		
		public System.Data.Linq.Table<tblAbgantBantOperator> tblAbgantBantOperators
		{
			get
			{
				return this.GetTable<tblAbgantBantOperator>();
			}
		}
		
		public System.Data.Linq.Table<tblAbgantBandDuraklama> tblAbgantBandDuraklamas
		{
			get
			{
				return this.GetTable<tblAbgantBandDuraklama>();
			}
		}
		
		public System.Data.Linq.Table<tblAbgantBand> tblAbgantBands
		{
			get
			{
				return this.GetTable<tblAbgantBand>();
			}
		}
		
		public System.Data.Linq.Table<tblAbgant> tblAbgants
		{
			get
			{
				return this.GetTable<tblAbgant>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUye")]
	public partial class tblUye : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uyeID;
		
		private string _kullaniciAdi;
		
		private string _sifre;
		
		private string _cepTel;
		
		private string _uyeTipi;
		
		private System.Nullable<bool> _status;
		
		private EntitySet<tblTeklifler> _tblTekliflers;
		
		private EntitySet<tblTalepler> _tblTaleplers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuyeIDChanging(int value);
    partial void OnuyeIDChanged();
    partial void OnkullaniciAdiChanging(string value);
    partial void OnkullaniciAdiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OncepTelChanging(string value);
    partial void OncepTelChanged();
    partial void OnuyeTipiChanging(string value);
    partial void OnuyeTipiChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    #endregion
		
		public tblUye()
		{
			this._tblTekliflers = new EntitySet<tblTeklifler>(new Action<tblTeklifler>(this.attach_tblTekliflers), new Action<tblTeklifler>(this.detach_tblTekliflers));
			this._tblTaleplers = new EntitySet<tblTalepler>(new Action<tblTalepler>(this.attach_tblTaleplers), new Action<tblTalepler>(this.detach_tblTaleplers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					this.OnuyeIDChanging(value);
					this.SendPropertyChanging();
					this._uyeID = value;
					this.SendPropertyChanged("uyeID");
					this.OnuyeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciAdi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string kullaniciAdi
		{
			get
			{
				return this._kullaniciAdi;
			}
			set
			{
				if ((this._kullaniciAdi != value))
				{
					this.OnkullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciAdi = value;
					this.SendPropertyChanged("kullaniciAdi");
					this.OnkullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(35) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cepTel", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string cepTel
		{
			get
			{
				return this._cepTel;
			}
			set
			{
				if ((this._cepTel != value))
				{
					this.OncepTelChanging(value);
					this.SendPropertyChanging();
					this._cepTel = value;
					this.SendPropertyChanged("cepTel");
					this.OncepTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeTipi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string uyeTipi
		{
			get
			{
				return this._uyeTipi;
			}
			set
			{
				if ((this._uyeTipi != value))
				{
					this.OnuyeTipiChanging(value);
					this.SendPropertyChanging();
					this._uyeTipi = value;
					this.SendPropertyChanged("uyeTipi");
					this.OnuyeTipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUye_tblTeklifler", Storage="_tblTekliflers", ThisKey="uyeID", OtherKey="uyeID")]
		public EntitySet<tblTeklifler> tblTekliflers
		{
			get
			{
				return this._tblTekliflers;
			}
			set
			{
				this._tblTekliflers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUye_tblTalepler", Storage="_tblTaleplers", ThisKey="uyeID", OtherKey="uyeID")]
		public EntitySet<tblTalepler> tblTaleplers
		{
			get
			{
				return this._tblTaleplers;
			}
			set
			{
				this._tblTaleplers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblTekliflers(tblTeklifler entity)
		{
			this.SendPropertyChanging();
			entity.tblUye = this;
		}
		
		private void detach_tblTekliflers(tblTeklifler entity)
		{
			this.SendPropertyChanging();
			entity.tblUye = null;
		}
		
		private void attach_tblTaleplers(tblTalepler entity)
		{
			this.SendPropertyChanging();
			entity.tblUye = this;
		}
		
		private void detach_tblTaleplers(tblTalepler entity)
		{
			this.SendPropertyChanging();
			entity.tblUye = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTeklifler")]
	public partial class tblTeklifler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _teklifID;
		
		private System.DateTime _teklifOlusturmaTarihi;
		
		private int _uyeID;
		
		private int _tedarikciID;
		
		private int _talepDetayID;
		
		private string _aciklama;
		
		private double _birimFiyat;
		
		private double _toplamFiyat;
		
		private System.DateTime _beklenenTeslimTarihi;
		
		private bool _status;
		
		private bool _isApproad;
		
		private bool _isDelivered;
		
		private System.DateTime _teslimEdilenTarih;
		
		private EntityRef<tblUye> _tblUye;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnteklifIDChanging(int value);
    partial void OnteklifIDChanged();
    partial void OnteklifOlusturmaTarihiChanging(System.DateTime value);
    partial void OnteklifOlusturmaTarihiChanged();
    partial void OnuyeIDChanging(int value);
    partial void OnuyeIDChanged();
    partial void OntedarikciIDChanging(int value);
    partial void OntedarikciIDChanged();
    partial void OntalepDetayIDChanging(int value);
    partial void OntalepDetayIDChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnbirimFiyatChanging(double value);
    partial void OnbirimFiyatChanged();
    partial void OntoplamFiyatChanging(double value);
    partial void OntoplamFiyatChanged();
    partial void OnbeklenenTeslimTarihiChanging(System.DateTime value);
    partial void OnbeklenenTeslimTarihiChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    partial void OnisApproadChanging(bool value);
    partial void OnisApproadChanged();
    partial void OnisDeliveredChanging(bool value);
    partial void OnisDeliveredChanged();
    partial void OnteslimEdilenTarihChanging(System.DateTime value);
    partial void OnteslimEdilenTarihChanged();
    #endregion
		
		public tblTeklifler()
		{
			this._tblUye = default(EntityRef<tblUye>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int teklifID
		{
			get
			{
				return this._teklifID;
			}
			set
			{
				if ((this._teklifID != value))
				{
					this.OnteklifIDChanging(value);
					this.SendPropertyChanging();
					this._teklifID = value;
					this.SendPropertyChanged("teklifID");
					this.OnteklifIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifOlusturmaTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime teklifOlusturmaTarihi
		{
			get
			{
				return this._teklifOlusturmaTarihi;
			}
			set
			{
				if ((this._teklifOlusturmaTarihi != value))
				{
					this.OnteklifOlusturmaTarihiChanging(value);
					this.SendPropertyChanging();
					this._teklifOlusturmaTarihi = value;
					this.SendPropertyChanged("teklifOlusturmaTarihi");
					this.OnteklifOlusturmaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", DbType="Int NOT NULL")]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					if (this._tblUye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuyeIDChanging(value);
					this.SendPropertyChanging();
					this._uyeID = value;
					this.SendPropertyChanged("uyeID");
					this.OnuyeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedarikciID", DbType="Int NOT NULL")]
		public int tedarikciID
		{
			get
			{
				return this._tedarikciID;
			}
			set
			{
				if ((this._tedarikciID != value))
				{
					this.OntedarikciIDChanging(value);
					this.SendPropertyChanging();
					this._tedarikciID = value;
					this.SendPropertyChanged("tedarikciID");
					this.OntedarikciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talepDetayID", DbType="Int NOT NULL")]
		public int talepDetayID
		{
			get
			{
				return this._talepDetayID;
			}
			set
			{
				if ((this._talepDetayID != value))
				{
					this.OntalepDetayIDChanging(value);
					this.SendPropertyChanging();
					this._talepDetayID = value;
					this.SendPropertyChanged("talepDetayID");
					this.OntalepDetayIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="VarChar(50)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birimFiyat", DbType="Float NOT NULL")]
		public double birimFiyat
		{
			get
			{
				return this._birimFiyat;
			}
			set
			{
				if ((this._birimFiyat != value))
				{
					this.OnbirimFiyatChanging(value);
					this.SendPropertyChanging();
					this._birimFiyat = value;
					this.SendPropertyChanged("birimFiyat");
					this.OnbirimFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_toplamFiyat", DbType="Float NOT NULL")]
		public double toplamFiyat
		{
			get
			{
				return this._toplamFiyat;
			}
			set
			{
				if ((this._toplamFiyat != value))
				{
					this.OntoplamFiyatChanging(value);
					this.SendPropertyChanging();
					this._toplamFiyat = value;
					this.SendPropertyChanged("toplamFiyat");
					this.OntoplamFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beklenenTeslimTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime beklenenTeslimTarihi
		{
			get
			{
				return this._beklenenTeslimTarihi;
			}
			set
			{
				if ((this._beklenenTeslimTarihi != value))
				{
					this.OnbeklenenTeslimTarihiChanging(value);
					this.SendPropertyChanging();
					this._beklenenTeslimTarihi = value;
					this.SendPropertyChanged("beklenenTeslimTarihi");
					this.OnbeklenenTeslimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isApproad", DbType="Bit NOT NULL")]
		public bool isApproad
		{
			get
			{
				return this._isApproad;
			}
			set
			{
				if ((this._isApproad != value))
				{
					this.OnisApproadChanging(value);
					this.SendPropertyChanging();
					this._isApproad = value;
					this.SendPropertyChanged("isApproad");
					this.OnisApproadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelivered", DbType="Bit NOT NULL")]
		public bool isDelivered
		{
			get
			{
				return this._isDelivered;
			}
			set
			{
				if ((this._isDelivered != value))
				{
					this.OnisDeliveredChanging(value);
					this.SendPropertyChanging();
					this._isDelivered = value;
					this.SendPropertyChanged("isDelivered");
					this.OnisDeliveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teslimEdilenTarih", DbType="DateTime NOT NULL")]
		public System.DateTime teslimEdilenTarih
		{
			get
			{
				return this._teslimEdilenTarih;
			}
			set
			{
				if ((this._teslimEdilenTarih != value))
				{
					this.OnteslimEdilenTarihChanging(value);
					this.SendPropertyChanging();
					this._teslimEdilenTarih = value;
					this.SendPropertyChanged("teslimEdilenTarih");
					this.OnteslimEdilenTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUye_tblTeklifler", Storage="_tblUye", ThisKey="uyeID", OtherKey="uyeID", IsForeignKey=true)]
		public tblUye tblUye
		{
			get
			{
				return this._tblUye.Entity;
			}
			set
			{
				tblUye previousValue = this._tblUye.Entity;
				if (((previousValue != value) 
							|| (this._tblUye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUye.Entity = null;
						previousValue.tblTekliflers.Remove(this);
					}
					this._tblUye.Entity = value;
					if ((value != null))
					{
						value.tblTekliflers.Add(this);
						this._uyeID = value.uyeID;
					}
					else
					{
						this._uyeID = default(int);
					}
					this.SendPropertyChanged("tblUye");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTedarikci")]
	public partial class tblTedarikci
	{
		
		private int _tedarikciID;
		
		private string _vergiNo;
		
		private string _tedarikciAdi;
		
		private string _yetkiliKisi;
		
		private string _telefon;
		
		private System.Nullable<double> _puan;
		
		private string _tedarikciTipi;
		
		private bool _status;
		
		public tblTedarikci()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedarikciID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int tedarikciID
		{
			get
			{
				return this._tedarikciID;
			}
			set
			{
				if ((this._tedarikciID != value))
				{
					this._tedarikciID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vergiNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string vergiNo
		{
			get
			{
				return this._vergiNo;
			}
			set
			{
				if ((this._vergiNo != value))
				{
					this._vergiNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedarikciAdi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string tedarikciAdi
		{
			get
			{
				return this._tedarikciAdi;
			}
			set
			{
				if ((this._tedarikciAdi != value))
				{
					this._tedarikciAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetkiliKisi", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string yetkiliKisi
		{
			get
			{
				return this._yetkiliKisi;
			}
			set
			{
				if ((this._yetkiliKisi != value))
				{
					this._yetkiliKisi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this._telefon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puan", DbType="Float")]
		public System.Nullable<double> puan
		{
			get
			{
				return this._puan;
			}
			set
			{
				if ((this._puan != value))
				{
					this._puan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tedarikciTipi", DbType="VarChar(15)")]
		public string tedarikciTipi
		{
			get
			{
				return this._tedarikciTipi;
			}
			set
			{
				if ((this._tedarikciTipi != value))
				{
					this._tedarikciTipi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTalepler")]
	public partial class tblTalepler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _talepID;
		
		private int _siparisID;
		
		private int _uyeID;
		
		private System.DateTime _talepTarihi;
		
		private EntityRef<tblUye> _tblUye;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntalepIDChanging(int value);
    partial void OntalepIDChanged();
    partial void OnsiparisIDChanging(int value);
    partial void OnsiparisIDChanged();
    partial void OnuyeIDChanging(int value);
    partial void OnuyeIDChanged();
    partial void OntalepTarihiChanging(System.DateTime value);
    partial void OntalepTarihiChanged();
    #endregion
		
		public tblTalepler()
		{
			this._tblUye = default(EntityRef<tblUye>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talepID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int talepID
		{
			get
			{
				return this._talepID;
			}
			set
			{
				if ((this._talepID != value))
				{
					this.OntalepIDChanging(value);
					this.SendPropertyChanging();
					this._talepID = value;
					this.SendPropertyChanged("talepID");
					this.OntalepIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisID", DbType="Int NOT NULL")]
		public int siparisID
		{
			get
			{
				return this._siparisID;
			}
			set
			{
				if ((this._siparisID != value))
				{
					this.OnsiparisIDChanging(value);
					this.SendPropertyChanging();
					this._siparisID = value;
					this.SendPropertyChanged("siparisID");
					this.OnsiparisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", DbType="Int NOT NULL")]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					if (this._tblUye.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnuyeIDChanging(value);
					this.SendPropertyChanging();
					this._uyeID = value;
					this.SendPropertyChanged("uyeID");
					this.OnuyeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talepTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime talepTarihi
		{
			get
			{
				return this._talepTarihi;
			}
			set
			{
				if ((this._talepTarihi != value))
				{
					this.OntalepTarihiChanging(value);
					this.SendPropertyChanging();
					this._talepTarihi = value;
					this.SendPropertyChanged("talepTarihi");
					this.OntalepTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblUye_tblTalepler", Storage="_tblUye", ThisKey="uyeID", OtherKey="uyeID", IsForeignKey=true)]
		public tblUye tblUye
		{
			get
			{
				return this._tblUye.Entity;
			}
			set
			{
				tblUye previousValue = this._tblUye.Entity;
				if (((previousValue != value) 
							|| (this._tblUye.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUye.Entity = null;
						previousValue.tblTaleplers.Remove(this);
					}
					this._tblUye.Entity = value;
					if ((value != null))
					{
						value.tblTaleplers.Add(this);
						this._uyeID = value.uyeID;
					}
					else
					{
						this._uyeID = default(int);
					}
					this.SendPropertyChanged("tblUye");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTalepDetay")]
	public partial class tblTalepDetay
	{
		
		private int _talepID;
		
		private int _malzemeID;
		
		private System.Nullable<double> _kalinlik;
		
		private System.Nullable<double> _en;
		
		private System.Nullable<double> _boy;
		
		private System.Nullable<double> _kg;
		
		private System.Nullable<int> _adet;
		
		private System.Nullable<System.DateTime> _uretimTarihi;
		
		private string _aciklama;
		
		public tblTalepDetay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_talepID", DbType="Int NOT NULL")]
		public int talepID
		{
			get
			{
				return this._talepID;
			}
			set
			{
				if ((this._talepID != value))
				{
					this._talepID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malzemeID", DbType="Int NOT NULL")]
		public int malzemeID
		{
			get
			{
				return this._malzemeID;
			}
			set
			{
				if ((this._malzemeID != value))
				{
					this._malzemeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kalinlik", DbType="Float")]
		public System.Nullable<double> kalinlik
		{
			get
			{
				return this._kalinlik;
			}
			set
			{
				if ((this._kalinlik != value))
				{
					this._kalinlik = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en", DbType="Float")]
		public System.Nullable<double> en
		{
			get
			{
				return this._en;
			}
			set
			{
				if ((this._en != value))
				{
					this._en = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_boy", DbType="Float")]
		public System.Nullable<double> boy
		{
			get
			{
				return this._boy;
			}
			set
			{
				if ((this._boy != value))
				{
					this._boy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kg", DbType="Float")]
		public System.Nullable<double> kg
		{
			get
			{
				return this._kg;
			}
			set
			{
				if ((this._kg != value))
				{
					this._kg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="Int")]
		public System.Nullable<int> adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this._adet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uretimTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> uretimTarihi
		{
			get
			{
				return this._uretimTarihi;
			}
			set
			{
				if ((this._uretimTarihi != value))
				{
					this._uretimTarihi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="VarChar(120)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this._aciklama = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblReceteler")]
	public partial class tblReceteler
	{
		
		private string _stokKodu;
		
		private System.Data.Linq.Binary _prosessSirasi;
		
		public tblReceteler()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokKodu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string stokKodu
		{
			get
			{
				return this._stokKodu;
			}
			set
			{
				if ((this._stokKodu != value))
				{
					this._stokKodu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prosessSirasi", DbType="Binary(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary prosessSirasi
		{
			get
			{
				return this._prosessSirasi;
			}
			set
			{
				if ((this._prosessSirasi != value))
				{
					this._prosessSirasi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPunchIsStoku")]
	public partial class tblPunchIsStoku : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _punchStokID;
		
		private int _siparisID;
		
		private string _stokKodu;
		
		private int _siparisAdedi;
		
		private int _uretilenAdet;
		
		private bool _isBand;
		
		private System.DateTime _bandGirisTarihi;
		
		private bool _isDelivered;
		
		private System.DateTime _bantBitistarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpunchStokIDChanging(int value);
    partial void OnpunchStokIDChanged();
    partial void OnsiparisIDChanging(int value);
    partial void OnsiparisIDChanged();
    partial void OnstokKoduChanging(string value);
    partial void OnstokKoduChanged();
    partial void OnsiparisAdediChanging(int value);
    partial void OnsiparisAdediChanged();
    partial void OnuretilenAdetChanging(int value);
    partial void OnuretilenAdetChanged();
    partial void OnisBandChanging(bool value);
    partial void OnisBandChanged();
    partial void OnbandGirisTarihiChanging(System.DateTime value);
    partial void OnbandGirisTarihiChanged();
    partial void OnisDeliveredChanging(bool value);
    partial void OnisDeliveredChanged();
    partial void OnbantBitistarihiChanging(System.DateTime value);
    partial void OnbantBitistarihiChanged();
    #endregion
		
		public tblPunchIsStoku()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchStokID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int punchStokID
		{
			get
			{
				return this._punchStokID;
			}
			set
			{
				if ((this._punchStokID != value))
				{
					this.OnpunchStokIDChanging(value);
					this.SendPropertyChanging();
					this._punchStokID = value;
					this.SendPropertyChanged("punchStokID");
					this.OnpunchStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisID", DbType="Int NOT NULL")]
		public int siparisID
		{
			get
			{
				return this._siparisID;
			}
			set
			{
				if ((this._siparisID != value))
				{
					this.OnsiparisIDChanging(value);
					this.SendPropertyChanging();
					this._siparisID = value;
					this.SendPropertyChanged("siparisID");
					this.OnsiparisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokKodu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string stokKodu
		{
			get
			{
				return this._stokKodu;
			}
			set
			{
				if ((this._stokKodu != value))
				{
					this.OnstokKoduChanging(value);
					this.SendPropertyChanging();
					this._stokKodu = value;
					this.SendPropertyChanged("stokKodu");
					this.OnstokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisAdedi", DbType="Int NOT NULL")]
		public int siparisAdedi
		{
			get
			{
				return this._siparisAdedi;
			}
			set
			{
				if ((this._siparisAdedi != value))
				{
					this.OnsiparisAdediChanging(value);
					this.SendPropertyChanging();
					this._siparisAdedi = value;
					this.SendPropertyChanged("siparisAdedi");
					this.OnsiparisAdediChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uretilenAdet", DbType="Int NOT NULL")]
		public int uretilenAdet
		{
			get
			{
				return this._uretilenAdet;
			}
			set
			{
				if ((this._uretilenAdet != value))
				{
					this.OnuretilenAdetChanging(value);
					this.SendPropertyChanging();
					this._uretilenAdet = value;
					this.SendPropertyChanged("uretilenAdet");
					this.OnuretilenAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isBand", DbType="Bit NOT NULL")]
		public bool isBand
		{
			get
			{
				return this._isBand;
			}
			set
			{
				if ((this._isBand != value))
				{
					this.OnisBandChanging(value);
					this.SendPropertyChanging();
					this._isBand = value;
					this.SendPropertyChanged("isBand");
					this.OnisBandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bandGirisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime bandGirisTarihi
		{
			get
			{
				return this._bandGirisTarihi;
			}
			set
			{
				if ((this._bandGirisTarihi != value))
				{
					this.OnbandGirisTarihiChanging(value);
					this.SendPropertyChanging();
					this._bandGirisTarihi = value;
					this.SendPropertyChanged("bandGirisTarihi");
					this.OnbandGirisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelivered", DbType="Bit NOT NULL")]
		public bool isDelivered
		{
			get
			{
				return this._isDelivered;
			}
			set
			{
				if ((this._isDelivered != value))
				{
					this.OnisDeliveredChanging(value);
					this.SendPropertyChanging();
					this._isDelivered = value;
					this.SendPropertyChanged("isDelivered");
					this.OnisDeliveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bantBitistarihi", DbType="DateTime NOT NULL")]
		public System.DateTime bantBitistarihi
		{
			get
			{
				return this._bantBitistarihi;
			}
			set
			{
				if ((this._bantBitistarihi != value))
				{
					this.OnbantBitistarihiChanging(value);
					this.SendPropertyChanging();
					this._bantBitistarihi = value;
					this.SendPropertyChanged("bantBitistarihi");
					this.OnbantBitistarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPunchBandOperator")]
	public partial class tblPunchBandOperator
	{
		
		private int _UyeID;
		
		private int _PunchID;
		
		public tblPunchBandOperator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UyeID", DbType="Int NOT NULL")]
		public int UyeID
		{
			get
			{
				return this._UyeID;
			}
			set
			{
				if ((this._UyeID != value))
				{
					this._UyeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PunchID", DbType="Int NOT NULL")]
		public int PunchID
		{
			get
			{
				return this._PunchID;
			}
			set
			{
				if ((this._PunchID != value))
				{
					this._PunchID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPunchBandDuraklama")]
	public partial class tblPunchBandDuraklama
	{
		
		private int _punchStokID;
		
		private int _punchBandID;
		
		private System.Nullable<System.DateTime> _durusZamani;
		
		private System.Nullable<System.DateTime> _yeniBaslamaZamani;
		
		private string _durusSebebi;
		
		private int _bitenMiktar;
		
		private int _bitenAdet;
		
		public tblPunchBandDuraklama()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchStokID", DbType="Int NOT NULL")]
		public int punchStokID
		{
			get
			{
				return this._punchStokID;
			}
			set
			{
				if ((this._punchStokID != value))
				{
					this._punchStokID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchBandID", DbType="Int NOT NULL")]
		public int punchBandID
		{
			get
			{
				return this._punchBandID;
			}
			set
			{
				if ((this._punchBandID != value))
				{
					this._punchBandID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durusZamani", DbType="DateTime")]
		public System.Nullable<System.DateTime> durusZamani
		{
			get
			{
				return this._durusZamani;
			}
			set
			{
				if ((this._durusZamani != value))
				{
					this._durusZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeniBaslamaZamani", DbType="DateTime")]
		public System.Nullable<System.DateTime> yeniBaslamaZamani
		{
			get
			{
				return this._yeniBaslamaZamani;
			}
			set
			{
				if ((this._yeniBaslamaZamani != value))
				{
					this._yeniBaslamaZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durusSebebi", DbType="VarChar(50)")]
		public string durusSebebi
		{
			get
			{
				return this._durusSebebi;
			}
			set
			{
				if ((this._durusSebebi != value))
				{
					this._durusSebebi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitenMiktar", DbType="Int NOT NULL")]
		public int bitenMiktar
		{
			get
			{
				return this._bitenMiktar;
			}
			set
			{
				if ((this._bitenMiktar != value))
				{
					this._bitenMiktar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitenAdet", DbType="Int NOT NULL")]
		public int bitenAdet
		{
			get
			{
				return this._bitenAdet;
			}
			set
			{
				if ((this._bitenAdet != value))
				{
					this._bitenAdet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPunchBand")]
	public partial class tblPunchBand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _punchBandID;
		
		private int _punchStokID;
		
		private int _punchID;
		
		private System.DateTime _baslamaSuresi;
		
		private System.DateTime _bitisSuresi;
		
		private int _siraNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpunchBandIDChanging(int value);
    partial void OnpunchBandIDChanged();
    partial void OnpunchStokIDChanging(int value);
    partial void OnpunchStokIDChanged();
    partial void OnpunchIDChanging(int value);
    partial void OnpunchIDChanged();
    partial void OnbaslamaSuresiChanging(System.DateTime value);
    partial void OnbaslamaSuresiChanged();
    partial void OnbitisSuresiChanging(System.DateTime value);
    partial void OnbitisSuresiChanged();
    partial void OnsiraNoChanging(int value);
    partial void OnsiraNoChanged();
    #endregion
		
		public tblPunchBand()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchBandID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int punchBandID
		{
			get
			{
				return this._punchBandID;
			}
			set
			{
				if ((this._punchBandID != value))
				{
					this.OnpunchBandIDChanging(value);
					this.SendPropertyChanging();
					this._punchBandID = value;
					this.SendPropertyChanged("punchBandID");
					this.OnpunchBandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchStokID", DbType="Int NOT NULL")]
		public int punchStokID
		{
			get
			{
				return this._punchStokID;
			}
			set
			{
				if ((this._punchStokID != value))
				{
					this.OnpunchStokIDChanging(value);
					this.SendPropertyChanging();
					this._punchStokID = value;
					this.SendPropertyChanged("punchStokID");
					this.OnpunchStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchID", DbType="Int NOT NULL")]
		public int punchID
		{
			get
			{
				return this._punchID;
			}
			set
			{
				if ((this._punchID != value))
				{
					this.OnpunchIDChanging(value);
					this.SendPropertyChanging();
					this._punchID = value;
					this.SendPropertyChanged("punchID");
					this.OnpunchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baslamaSuresi", DbType="DateTime NOT NULL")]
		public System.DateTime baslamaSuresi
		{
			get
			{
				return this._baslamaSuresi;
			}
			set
			{
				if ((this._baslamaSuresi != value))
				{
					this.OnbaslamaSuresiChanging(value);
					this.SendPropertyChanging();
					this._baslamaSuresi = value;
					this.SendPropertyChanged("baslamaSuresi");
					this.OnbaslamaSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitisSuresi", DbType="DateTime NOT NULL")]
		public System.DateTime bitisSuresi
		{
			get
			{
				return this._bitisSuresi;
			}
			set
			{
				if ((this._bitisSuresi != value))
				{
					this.OnbitisSuresiChanging(value);
					this.SendPropertyChanging();
					this._bitisSuresi = value;
					this.SendPropertyChanged("bitisSuresi");
					this.OnbitisSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siraNo", DbType="Int NOT NULL")]
		public int siraNo
		{
			get
			{
				return this._siraNo;
			}
			set
			{
				if ((this._siraNo != value))
				{
					this.OnsiraNoChanging(value);
					this.SendPropertyChanging();
					this._siraNo = value;
					this.SendPropertyChanged("siraNo");
					this.OnsiraNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPunch")]
	public partial class tblPunch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _punchID;
		
		private string _punchName;
		
		private System.Data.Linq.Binary _punchFoto;
		
		private string _ozellikleri;
		
		private string _aciklama;
		
		private bool _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpunchIDChanging(int value);
    partial void OnpunchIDChanged();
    partial void OnpunchNameChanging(string value);
    partial void OnpunchNameChanged();
    partial void OnpunchFotoChanging(System.Data.Linq.Binary value);
    partial void OnpunchFotoChanged();
    partial void OnozellikleriChanging(string value);
    partial void OnozellikleriChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    #endregion
		
		public tblPunch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int punchID
		{
			get
			{
				return this._punchID;
			}
			set
			{
				if ((this._punchID != value))
				{
					this.OnpunchIDChanging(value);
					this.SendPropertyChanging();
					this._punchID = value;
					this.SendPropertyChanged("punchID");
					this.OnpunchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchName", DbType="NVarChar(50)")]
		public string punchName
		{
			get
			{
				return this._punchName;
			}
			set
			{
				if ((this._punchName != value))
				{
					this.OnpunchNameChanging(value);
					this.SendPropertyChanging();
					this._punchName = value;
					this.SendPropertyChanged("punchName");
					this.OnpunchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_punchFoto", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary punchFoto
		{
			get
			{
				return this._punchFoto;
			}
			set
			{
				if ((this._punchFoto != value))
				{
					this.OnpunchFotoChanging(value);
					this.SendPropertyChanging();
					this._punchFoto = value;
					this.SendPropertyChanged("punchFoto");
					this.OnpunchFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ozellikleri", DbType="NVarChar(50)")]
		public string ozellikleri
		{
			get
			{
				return this._ozellikleri;
			}
			set
			{
				if ((this._ozellikleri != value))
				{
					this.OnozellikleriChanging(value);
					this.SendPropertyChanging();
					this._ozellikleri = value;
					this.SendPropertyChanged("ozellikleri");
					this.OnozellikleriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="NVarChar(50)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMalzeme")]
	public partial class tblMalzeme : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _malzemeID;
		
		private string _malzemeAdi;
		
		private string _aciklama;
		
		private string _type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmalzemeIDChanging(int value);
    partial void OnmalzemeIDChanged();
    partial void OnmalzemeAdiChanging(string value);
    partial void OnmalzemeAdiChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public tblMalzeme()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malzemeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int malzemeID
		{
			get
			{
				return this._malzemeID;
			}
			set
			{
				if ((this._malzemeID != value))
				{
					this.OnmalzemeIDChanging(value);
					this.SendPropertyChanging();
					this._malzemeID = value;
					this.SendPropertyChanged("malzemeID");
					this.OnmalzemeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_malzemeAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string malzemeAdi
		{
			get
			{
				return this._malzemeAdi;
			}
			set
			{
				if ((this._malzemeAdi != value))
				{
					this.OnmalzemeAdiChanging(value);
					this.SendPropertyChanging();
					this._malzemeAdi = value;
					this.SendPropertyChanged("malzemeAdi");
					this.OnmalzemeAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="NVarChar(MAX)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLazerStok")]
	public partial class tblLazerStok : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LStokID;
		
		private System.DateTime _stokGirisTarihi;
		
		private int _siparisID;
		
		private string _stokKodu;
		
		private bool _isBand;
		
		private System.DateTime _bandGirisTarihi;
		
		private bool _isdelivered;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLStokIDChanging(int value);
    partial void OnLStokIDChanged();
    partial void OnstokGirisTarihiChanging(System.DateTime value);
    partial void OnstokGirisTarihiChanged();
    partial void OnsiparisIDChanging(int value);
    partial void OnsiparisIDChanged();
    partial void OnstokKoduChanging(string value);
    partial void OnstokKoduChanged();
    partial void OnisBandChanging(bool value);
    partial void OnisBandChanged();
    partial void OnbandGirisTarihiChanging(System.DateTime value);
    partial void OnbandGirisTarihiChanged();
    partial void OnisdeliveredChanging(bool value);
    partial void OnisdeliveredChanged();
    #endregion
		
		public tblLazerStok()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LStokID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LStokID
		{
			get
			{
				return this._LStokID;
			}
			set
			{
				if ((this._LStokID != value))
				{
					this.OnLStokIDChanging(value);
					this.SendPropertyChanging();
					this._LStokID = value;
					this.SendPropertyChanged("LStokID");
					this.OnLStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokGirisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime stokGirisTarihi
		{
			get
			{
				return this._stokGirisTarihi;
			}
			set
			{
				if ((this._stokGirisTarihi != value))
				{
					this.OnstokGirisTarihiChanging(value);
					this.SendPropertyChanging();
					this._stokGirisTarihi = value;
					this.SendPropertyChanged("stokGirisTarihi");
					this.OnstokGirisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisID", DbType="Int NOT NULL")]
		public int siparisID
		{
			get
			{
				return this._siparisID;
			}
			set
			{
				if ((this._siparisID != value))
				{
					this.OnsiparisIDChanging(value);
					this.SendPropertyChanging();
					this._siparisID = value;
					this.SendPropertyChanged("siparisID");
					this.OnsiparisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokKodu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string stokKodu
		{
			get
			{
				return this._stokKodu;
			}
			set
			{
				if ((this._stokKodu != value))
				{
					this.OnstokKoduChanging(value);
					this.SendPropertyChanging();
					this._stokKodu = value;
					this.SendPropertyChanged("stokKodu");
					this.OnstokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isBand", DbType="Bit NOT NULL")]
		public bool isBand
		{
			get
			{
				return this._isBand;
			}
			set
			{
				if ((this._isBand != value))
				{
					this.OnisBandChanging(value);
					this.SendPropertyChanging();
					this._isBand = value;
					this.SendPropertyChanged("isBand");
					this.OnisBandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bandGirisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime bandGirisTarihi
		{
			get
			{
				return this._bandGirisTarihi;
			}
			set
			{
				if ((this._bandGirisTarihi != value))
				{
					this.OnbandGirisTarihiChanging(value);
					this.SendPropertyChanging();
					this._bandGirisTarihi = value;
					this.SendPropertyChanged("bandGirisTarihi");
					this.OnbandGirisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdelivered", DbType="Bit NOT NULL")]
		public bool isdelivered
		{
			get
			{
				return this._isdelivered;
			}
			set
			{
				if ((this._isdelivered != value))
				{
					this.OnisdeliveredChanging(value);
					this.SendPropertyChanging();
					this._isdelivered = value;
					this.SendPropertyChanged("isdelivered");
					this.OnisdeliveredChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLazerBantOperator")]
	public partial class tblLazerBantOperator
	{
		
		private int _uyeID;
		
		private int _lazerID;
		
		public tblLazerBantOperator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", DbType="Int NOT NULL")]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					this._uyeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lazerID", DbType="Int NOT NULL")]
		public int lazerID
		{
			get
			{
				return this._lazerID;
			}
			set
			{
				if ((this._lazerID != value))
				{
					this._lazerID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLazerBantDuraklama")]
	public partial class tblLazerBantDuraklama
	{
		
		private int _lazerStokID;
		
		private int _lazerBantID;
		
		private System.DateTime _LdurusZamani;
		
		private System.DateTime _LyeniBaslamaZamani;
		
		private string _LdurusSebebi;
		
		private int _LbitenMiktar;
		
		private int _LbitenAdet;
		
		public tblLazerBantDuraklama()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lazerStokID", DbType="Int NOT NULL")]
		public int lazerStokID
		{
			get
			{
				return this._lazerStokID;
			}
			set
			{
				if ((this._lazerStokID != value))
				{
					this._lazerStokID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lazerBantID", DbType="Int NOT NULL")]
		public int lazerBantID
		{
			get
			{
				return this._lazerBantID;
			}
			set
			{
				if ((this._lazerBantID != value))
				{
					this._lazerBantID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LdurusZamani", DbType="DateTime NOT NULL")]
		public System.DateTime LdurusZamani
		{
			get
			{
				return this._LdurusZamani;
			}
			set
			{
				if ((this._LdurusZamani != value))
				{
					this._LdurusZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyeniBaslamaZamani", DbType="DateTime NOT NULL")]
		public System.DateTime LyeniBaslamaZamani
		{
			get
			{
				return this._LyeniBaslamaZamani;
			}
			set
			{
				if ((this._LyeniBaslamaZamani != value))
				{
					this._LyeniBaslamaZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LdurusSebebi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LdurusSebebi
		{
			get
			{
				return this._LdurusSebebi;
			}
			set
			{
				if ((this._LdurusSebebi != value))
				{
					this._LdurusSebebi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LbitenMiktar", DbType="Int NOT NULL")]
		public int LbitenMiktar
		{
			get
			{
				return this._LbitenMiktar;
			}
			set
			{
				if ((this._LbitenMiktar != value))
				{
					this._LbitenMiktar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LbitenAdet", DbType="Int NOT NULL")]
		public int LbitenAdet
		{
			get
			{
				return this._LbitenAdet;
			}
			set
			{
				if ((this._LbitenAdet != value))
				{
					this._LbitenAdet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLazerBand")]
	public partial class tblLazerBand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LazerBandID;
		
		private int _LazerStokID;
		
		private int _LazerID;
		
		private string _BaslamaSuresi;
		
		private string _BitisSuresi;
		
		private int _SiraNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLazerBandIDChanging(int value);
    partial void OnLazerBandIDChanged();
    partial void OnLazerStokIDChanging(int value);
    partial void OnLazerStokIDChanged();
    partial void OnLazerIDChanging(int value);
    partial void OnLazerIDChanged();
    partial void OnBaslamaSuresiChanging(string value);
    partial void OnBaslamaSuresiChanged();
    partial void OnBitisSuresiChanging(string value);
    partial void OnBitisSuresiChanged();
    partial void OnSiraNoChanging(int value);
    partial void OnSiraNoChanged();
    #endregion
		
		public tblLazerBand()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LazerBandID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LazerBandID
		{
			get
			{
				return this._LazerBandID;
			}
			set
			{
				if ((this._LazerBandID != value))
				{
					this.OnLazerBandIDChanging(value);
					this.SendPropertyChanging();
					this._LazerBandID = value;
					this.SendPropertyChanged("LazerBandID");
					this.OnLazerBandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LazerStokID", DbType="Int NOT NULL")]
		public int LazerStokID
		{
			get
			{
				return this._LazerStokID;
			}
			set
			{
				if ((this._LazerStokID != value))
				{
					this.OnLazerStokIDChanging(value);
					this.SendPropertyChanging();
					this._LazerStokID = value;
					this.SendPropertyChanged("LazerStokID");
					this.OnLazerStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LazerID", DbType="Int NOT NULL")]
		public int LazerID
		{
			get
			{
				return this._LazerID;
			}
			set
			{
				if ((this._LazerID != value))
				{
					this.OnLazerIDChanging(value);
					this.SendPropertyChanging();
					this._LazerID = value;
					this.SendPropertyChanged("LazerID");
					this.OnLazerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaslamaSuresi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string BaslamaSuresi
		{
			get
			{
				return this._BaslamaSuresi;
			}
			set
			{
				if ((this._BaslamaSuresi != value))
				{
					this.OnBaslamaSuresiChanging(value);
					this.SendPropertyChanging();
					this._BaslamaSuresi = value;
					this.SendPropertyChanged("BaslamaSuresi");
					this.OnBaslamaSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisSuresi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string BitisSuresi
		{
			get
			{
				return this._BitisSuresi;
			}
			set
			{
				if ((this._BitisSuresi != value))
				{
					this.OnBitisSuresiChanging(value);
					this.SendPropertyChanging();
					this._BitisSuresi = value;
					this.SendPropertyChanged("BitisSuresi");
					this.OnBitisSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiraNo", DbType="Int NOT NULL")]
		public int SiraNo
		{
			get
			{
				return this._SiraNo;
			}
			set
			{
				if ((this._SiraNo != value))
				{
					this.OnSiraNoChanging(value);
					this.SendPropertyChanging();
					this._SiraNo = value;
					this.SendPropertyChanged("SiraNo");
					this.OnSiraNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLazer")]
	public partial class tblLazer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lazerID;
		
		private string _lazerName;
		
		private System.Data.Linq.Binary _lazerFoto;
		
		private string _ozellikleri;
		
		private string _aciklama;
		
		private bool _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlazerIDChanging(int value);
    partial void OnlazerIDChanged();
    partial void OnlazerNameChanging(string value);
    partial void OnlazerNameChanged();
    partial void OnlazerFotoChanging(System.Data.Linq.Binary value);
    partial void OnlazerFotoChanged();
    partial void OnozellikleriChanging(string value);
    partial void OnozellikleriChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    #endregion
		
		public tblLazer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lazerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lazerID
		{
			get
			{
				return this._lazerID;
			}
			set
			{
				if ((this._lazerID != value))
				{
					this.OnlazerIDChanging(value);
					this.SendPropertyChanging();
					this._lazerID = value;
					this.SendPropertyChanged("lazerID");
					this.OnlazerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lazerName", DbType="NVarChar(50)")]
		public string lazerName
		{
			get
			{
				return this._lazerName;
			}
			set
			{
				if ((this._lazerName != value))
				{
					this.OnlazerNameChanging(value);
					this.SendPropertyChanging();
					this._lazerName = value;
					this.SendPropertyChanged("lazerName");
					this.OnlazerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lazerFoto", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary lazerFoto
		{
			get
			{
				return this._lazerFoto;
			}
			set
			{
				if ((this._lazerFoto != value))
				{
					this.OnlazerFotoChanging(value);
					this.SendPropertyChanging();
					this._lazerFoto = value;
					this.SendPropertyChanged("lazerFoto");
					this.OnlazerFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ozellikleri", DbType="NVarChar(50)")]
		public string ozellikleri
		{
			get
			{
				return this._ozellikleri;
			}
			set
			{
				if ((this._ozellikleri != value))
				{
					this.OnozellikleriChanging(value);
					this.SendPropertyChanging();
					this._ozellikleri = value;
					this.SendPropertyChanged("ozellikleri");
					this.OnozellikleriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="NVarChar(50)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblgenelIsStok")]
	public partial class tblgenelIsStok : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _genelID;
		
		private string _siparisKodu;
		
		private string _stokKodu;
		
		private System.DateTime _siparisTarihi;
		
		private int _cariKodu;
		
		private int _adet;
		
		private System.DateTime _teslimTarihi;
		
		private bool _isdelivered;
		
		private System.DateTime _planlamaTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngenelIDChanging(int value);
    partial void OngenelIDChanged();
    partial void OnsiparisKoduChanging(string value);
    partial void OnsiparisKoduChanged();
    partial void OnstokKoduChanging(string value);
    partial void OnstokKoduChanged();
    partial void OnsiparisTarihiChanging(System.DateTime value);
    partial void OnsiparisTarihiChanged();
    partial void OncariKoduChanging(int value);
    partial void OncariKoduChanged();
    partial void OnadetChanging(int value);
    partial void OnadetChanged();
    partial void OnteslimTarihiChanging(System.DateTime value);
    partial void OnteslimTarihiChanged();
    partial void OnisdeliveredChanging(bool value);
    partial void OnisdeliveredChanged();
    partial void OnplanlamaTarihiChanging(System.DateTime value);
    partial void OnplanlamaTarihiChanged();
    #endregion
		
		public tblgenelIsStok()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genelID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int genelID
		{
			get
			{
				return this._genelID;
			}
			set
			{
				if ((this._genelID != value))
				{
					this.OngenelIDChanging(value);
					this.SendPropertyChanging();
					this._genelID = value;
					this.SendPropertyChanged("genelID");
					this.OngenelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisKodu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siparisKodu
		{
			get
			{
				return this._siparisKodu;
			}
			set
			{
				if ((this._siparisKodu != value))
				{
					this.OnsiparisKoduChanging(value);
					this.SendPropertyChanging();
					this._siparisKodu = value;
					this.SendPropertyChanged("siparisKodu");
					this.OnsiparisKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokKodu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string stokKodu
		{
			get
			{
				return this._stokKodu;
			}
			set
			{
				if ((this._stokKodu != value))
				{
					this.OnstokKoduChanging(value);
					this.SendPropertyChanging();
					this._stokKodu = value;
					this.SendPropertyChanged("stokKodu");
					this.OnstokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime siparisTarihi
		{
			get
			{
				return this._siparisTarihi;
			}
			set
			{
				if ((this._siparisTarihi != value))
				{
					this.OnsiparisTarihiChanging(value);
					this.SendPropertyChanging();
					this._siparisTarihi = value;
					this.SendPropertyChanged("siparisTarihi");
					this.OnsiparisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariKodu", DbType="Int NOT NULL")]
		public int cariKodu
		{
			get
			{
				return this._cariKodu;
			}
			set
			{
				if ((this._cariKodu != value))
				{
					this.OncariKoduChanging(value);
					this.SendPropertyChanging();
					this._cariKodu = value;
					this.SendPropertyChanged("cariKodu");
					this.OncariKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="Int NOT NULL")]
		public int adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teslimTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime teslimTarihi
		{
			get
			{
				return this._teslimTarihi;
			}
			set
			{
				if ((this._teslimTarihi != value))
				{
					this.OnteslimTarihiChanging(value);
					this.SendPropertyChanging();
					this._teslimTarihi = value;
					this.SendPropertyChanged("teslimTarihi");
					this.OnteslimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isdelivered", DbType="Bit NOT NULL")]
		public bool isdelivered
		{
			get
			{
				return this._isdelivered;
			}
			set
			{
				if ((this._isdelivered != value))
				{
					this.OnisdeliveredChanging(value);
					this.SendPropertyChanging();
					this._isdelivered = value;
					this.SendPropertyChanged("isdelivered");
					this.OnisdeliveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planlamaTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime planlamaTarihi
		{
			get
			{
				return this._planlamaTarihi;
			}
			set
			{
				if ((this._planlamaTarihi != value))
				{
					this.OnplanlamaTarihiChanging(value);
					this.SendPropertyChanging();
					this._planlamaTarihi = value;
					this.SendPropertyChanged("planlamaTarihi");
					this.OnplanlamaTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblError")]
	public partial class tblError : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ErrorId;
		
		private string _aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnErrorIdChanging(int value);
    partial void OnErrorIdChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    #endregion
		
		public tblError()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ErrorId
		{
			get
			{
				return this._ErrorId;
			}
			set
			{
				if ((this._ErrorId != value))
				{
					this.OnErrorIdChanging(value);
					this.SendPropertyChanging();
					this._ErrorId = value;
					this.SendPropertyChanged("ErrorId");
					this.OnErrorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAbgantIsStoku")]
	public partial class tblAbgantIsStoku : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _abgantStokID;
		
		private int _siparisID;
		
		private string _stokKodu;
		
		private int _siparisAdedi;
		
		private int _uretilenAdet;
		
		private bool _isBand;
		
		private System.DateTime _bandGirisTarihi;
		
		private bool _isDelivered;
		
		private System.DateTime _bantBitisTarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnabgantStokIDChanging(int value);
    partial void OnabgantStokIDChanged();
    partial void OnsiparisIDChanging(int value);
    partial void OnsiparisIDChanged();
    partial void OnstokKoduChanging(string value);
    partial void OnstokKoduChanged();
    partial void OnsiparisAdediChanging(int value);
    partial void OnsiparisAdediChanged();
    partial void OnuretilenAdetChanging(int value);
    partial void OnuretilenAdetChanged();
    partial void OnisBandChanging(bool value);
    partial void OnisBandChanged();
    partial void OnbandGirisTarihiChanging(System.DateTime value);
    partial void OnbandGirisTarihiChanged();
    partial void OnisDeliveredChanging(bool value);
    partial void OnisDeliveredChanged();
    partial void OnbantBitisTarihiChanging(System.DateTime value);
    partial void OnbantBitisTarihiChanged();
    #endregion
		
		public tblAbgantIsStoku()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantStokID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int abgantStokID
		{
			get
			{
				return this._abgantStokID;
			}
			set
			{
				if ((this._abgantStokID != value))
				{
					this.OnabgantStokIDChanging(value);
					this.SendPropertyChanging();
					this._abgantStokID = value;
					this.SendPropertyChanged("abgantStokID");
					this.OnabgantStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisID", DbType="Int NOT NULL")]
		public int siparisID
		{
			get
			{
				return this._siparisID;
			}
			set
			{
				if ((this._siparisID != value))
				{
					this.OnsiparisIDChanging(value);
					this.SendPropertyChanging();
					this._siparisID = value;
					this.SendPropertyChanged("siparisID");
					this.OnsiparisIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokKodu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string stokKodu
		{
			get
			{
				return this._stokKodu;
			}
			set
			{
				if ((this._stokKodu != value))
				{
					this.OnstokKoduChanging(value);
					this.SendPropertyChanging();
					this._stokKodu = value;
					this.SendPropertyChanged("stokKodu");
					this.OnstokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisAdedi", DbType="Int NOT NULL")]
		public int siparisAdedi
		{
			get
			{
				return this._siparisAdedi;
			}
			set
			{
				if ((this._siparisAdedi != value))
				{
					this.OnsiparisAdediChanging(value);
					this.SendPropertyChanging();
					this._siparisAdedi = value;
					this.SendPropertyChanged("siparisAdedi");
					this.OnsiparisAdediChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uretilenAdet", DbType="Int NOT NULL")]
		public int uretilenAdet
		{
			get
			{
				return this._uretilenAdet;
			}
			set
			{
				if ((this._uretilenAdet != value))
				{
					this.OnuretilenAdetChanging(value);
					this.SendPropertyChanging();
					this._uretilenAdet = value;
					this.SendPropertyChanged("uretilenAdet");
					this.OnuretilenAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isBand", DbType="Bit NOT NULL")]
		public bool isBand
		{
			get
			{
				return this._isBand;
			}
			set
			{
				if ((this._isBand != value))
				{
					this.OnisBandChanging(value);
					this.SendPropertyChanging();
					this._isBand = value;
					this.SendPropertyChanged("isBand");
					this.OnisBandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bandGirisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime bandGirisTarihi
		{
			get
			{
				return this._bandGirisTarihi;
			}
			set
			{
				if ((this._bandGirisTarihi != value))
				{
					this.OnbandGirisTarihiChanging(value);
					this.SendPropertyChanging();
					this._bandGirisTarihi = value;
					this.SendPropertyChanged("bandGirisTarihi");
					this.OnbandGirisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDelivered", DbType="Bit NOT NULL")]
		public bool isDelivered
		{
			get
			{
				return this._isDelivered;
			}
			set
			{
				if ((this._isDelivered != value))
				{
					this.OnisDeliveredChanging(value);
					this.SendPropertyChanging();
					this._isDelivered = value;
					this.SendPropertyChanged("isDelivered");
					this.OnisDeliveredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bantBitisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime bantBitisTarihi
		{
			get
			{
				return this._bantBitisTarihi;
			}
			set
			{
				if ((this._bantBitisTarihi != value))
				{
					this.OnbantBitisTarihiChanging(value);
					this.SendPropertyChanging();
					this._bantBitisTarihi = value;
					this.SendPropertyChanged("bantBitisTarihi");
					this.OnbantBitisTarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAbgantBantOperator")]
	public partial class tblAbgantBantOperator
	{
		
		private int _uyeID;
		
		private int _abgantID;
		
		public tblAbgantBantOperator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uyeID", DbType="Int NOT NULL")]
		public int uyeID
		{
			get
			{
				return this._uyeID;
			}
			set
			{
				if ((this._uyeID != value))
				{
					this._uyeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantID", DbType="Int NOT NULL")]
		public int abgantID
		{
			get
			{
				return this._abgantID;
			}
			set
			{
				if ((this._abgantID != value))
				{
					this._abgantID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAbgantBandDuraklama")]
	public partial class tblAbgantBandDuraklama
	{
		
		private int _abgantStokID;
		
		private int _abgantBantID;
		
		private System.DateTime _durusZamani;
		
		private System.DateTime _yeniBaslamaZamani;
		
		private string _durusSebebi;
		
		private int _bitenMiktar;
		
		private int _bitenAdet;
		
		public tblAbgantBandDuraklama()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantStokID", DbType="Int NOT NULL")]
		public int abgantStokID
		{
			get
			{
				return this._abgantStokID;
			}
			set
			{
				if ((this._abgantStokID != value))
				{
					this._abgantStokID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantBantID", DbType="Int NOT NULL")]
		public int abgantBantID
		{
			get
			{
				return this._abgantBantID;
			}
			set
			{
				if ((this._abgantBantID != value))
				{
					this._abgantBantID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durusZamani", DbType="DateTime NOT NULL")]
		public System.DateTime durusZamani
		{
			get
			{
				return this._durusZamani;
			}
			set
			{
				if ((this._durusZamani != value))
				{
					this._durusZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yeniBaslamaZamani", DbType="DateTime NOT NULL")]
		public System.DateTime yeniBaslamaZamani
		{
			get
			{
				return this._yeniBaslamaZamani;
			}
			set
			{
				if ((this._yeniBaslamaZamani != value))
				{
					this._yeniBaslamaZamani = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durusSebebi", DbType="NVarChar(50)")]
		public string durusSebebi
		{
			get
			{
				return this._durusSebebi;
			}
			set
			{
				if ((this._durusSebebi != value))
				{
					this._durusSebebi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitenMiktar", DbType="Int NOT NULL")]
		public int bitenMiktar
		{
			get
			{
				return this._bitenMiktar;
			}
			set
			{
				if ((this._bitenMiktar != value))
				{
					this._bitenMiktar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitenAdet", DbType="Int NOT NULL")]
		public int bitenAdet
		{
			get
			{
				return this._bitenAdet;
			}
			set
			{
				if ((this._bitenAdet != value))
				{
					this._bitenAdet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAbgantBand")]
	public partial class tblAbgantBand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AbgantBandID;
		
		private int _AbgantStokID;
		
		private int _AbgantID;
		
		private string _BaslamaSuresi;
		
		private string _BitisSuresi;
		
		private int _SiraNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAbgantBandIDChanging(int value);
    partial void OnAbgantBandIDChanged();
    partial void OnAbgantStokIDChanging(int value);
    partial void OnAbgantStokIDChanged();
    partial void OnAbgantIDChanging(int value);
    partial void OnAbgantIDChanged();
    partial void OnBaslamaSuresiChanging(string value);
    partial void OnBaslamaSuresiChanged();
    partial void OnBitisSuresiChanging(string value);
    partial void OnBitisSuresiChanged();
    partial void OnSiraNoChanging(int value);
    partial void OnSiraNoChanged();
    #endregion
		
		public tblAbgantBand()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbgantBandID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AbgantBandID
		{
			get
			{
				return this._AbgantBandID;
			}
			set
			{
				if ((this._AbgantBandID != value))
				{
					this.OnAbgantBandIDChanging(value);
					this.SendPropertyChanging();
					this._AbgantBandID = value;
					this.SendPropertyChanged("AbgantBandID");
					this.OnAbgantBandIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbgantStokID", DbType="Int NOT NULL")]
		public int AbgantStokID
		{
			get
			{
				return this._AbgantStokID;
			}
			set
			{
				if ((this._AbgantStokID != value))
				{
					this.OnAbgantStokIDChanging(value);
					this.SendPropertyChanging();
					this._AbgantStokID = value;
					this.SendPropertyChanged("AbgantStokID");
					this.OnAbgantStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbgantID", DbType="Int NOT NULL")]
		public int AbgantID
		{
			get
			{
				return this._AbgantID;
			}
			set
			{
				if ((this._AbgantID != value))
				{
					this.OnAbgantIDChanging(value);
					this.SendPropertyChanging();
					this._AbgantID = value;
					this.SendPropertyChanged("AbgantID");
					this.OnAbgantIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaslamaSuresi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string BaslamaSuresi
		{
			get
			{
				return this._BaslamaSuresi;
			}
			set
			{
				if ((this._BaslamaSuresi != value))
				{
					this.OnBaslamaSuresiChanging(value);
					this.SendPropertyChanging();
					this._BaslamaSuresi = value;
					this.SendPropertyChanged("BaslamaSuresi");
					this.OnBaslamaSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BitisSuresi", DbType="VarChar(35) NOT NULL", CanBeNull=false)]
		public string BitisSuresi
		{
			get
			{
				return this._BitisSuresi;
			}
			set
			{
				if ((this._BitisSuresi != value))
				{
					this.OnBitisSuresiChanging(value);
					this.SendPropertyChanging();
					this._BitisSuresi = value;
					this.SendPropertyChanged("BitisSuresi");
					this.OnBitisSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SiraNo", DbType="Int NOT NULL")]
		public int SiraNo
		{
			get
			{
				return this._SiraNo;
			}
			set
			{
				if ((this._SiraNo != value))
				{
					this.OnSiraNoChanging(value);
					this.SendPropertyChanging();
					this._SiraNo = value;
					this.SendPropertyChanged("SiraNo");
					this.OnSiraNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAbgant")]
	public partial class tblAbgant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _abgantID;
		
		private string _abgantName;
		
		private System.Data.Linq.Binary _abgantFoto;
		
		private string _ozellikleri;
		
		private string _aciklama;
		
		private bool _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnabgantIDChanging(int value);
    partial void OnabgantIDChanged();
    partial void OnabgantNameChanging(string value);
    partial void OnabgantNameChanged();
    partial void OnabgantFotoChanging(System.Data.Linq.Binary value);
    partial void OnabgantFotoChanged();
    partial void OnozellikleriChanging(string value);
    partial void OnozellikleriChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnstatusChanging(bool value);
    partial void OnstatusChanged();
    #endregion
		
		public tblAbgant()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int abgantID
		{
			get
			{
				return this._abgantID;
			}
			set
			{
				if ((this._abgantID != value))
				{
					this.OnabgantIDChanging(value);
					this.SendPropertyChanging();
					this._abgantID = value;
					this.SendPropertyChanged("abgantID");
					this.OnabgantIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string abgantName
		{
			get
			{
				return this._abgantName;
			}
			set
			{
				if ((this._abgantName != value))
				{
					this.OnabgantNameChanging(value);
					this.SendPropertyChanging();
					this._abgantName = value;
					this.SendPropertyChanged("abgantName");
					this.OnabgantNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abgantFoto", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary abgantFoto
		{
			get
			{
				return this._abgantFoto;
			}
			set
			{
				if ((this._abgantFoto != value))
				{
					this.OnabgantFotoChanging(value);
					this.SendPropertyChanging();
					this._abgantFoto = value;
					this.SendPropertyChanged("abgantFoto");
					this.OnabgantFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ozellikleri", DbType="NVarChar(50)")]
		public string ozellikleri
		{
			get
			{
				return this._ozellikleri;
			}
			set
			{
				if ((this._ozellikleri != value))
				{
					this.OnozellikleriChanging(value);
					this.SendPropertyChanging();
					this._ozellikleri = value;
					this.SendPropertyChanged("ozellikleri");
					this.OnozellikleriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="NVarChar(50)")]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit NOT NULL")]
		public bool status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
